apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fusioniq 
  labels:
    name: backend
    project: fusioniq
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
      name: backend
      project: fusioniq
      tier: app
      env: {{ .Values.deployment.environment }}
  template: 
    metadata:
      labels: 
        name: backend
        project: fusioniq
        tier: app
        env: {{ .Values.deployment.environment }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: SPRING_DATASOURCE_URL  # Fixed Name
          valueFrom:
            configMapKeyRef:
              name: backend
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_PASSWORD