apiVersion: v1
kind: Secret
metadata:
  name: backend-{{ .Values.deployment.replicas }}
  namespace: fusioniq
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.db.password }}  # Base64 for password
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.username }}