apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: fusioniq
spec:
  type: LoadBalancer # NodePort
  selector:
    name: web
    project: fusioniq
    tier: web 
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port