apiVersion: v1
kind: Service
metadata:
  name: web-{{ .Values.deployment.replicas }}
  namespace: fusioniq
spec:
  selector:
    name: web-{{ .Values.deployment.replicas }}
    project: fusioniq
    tier: web 
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port