deployment:
  replicas: 1
  environment: blue
image:
  repository: iamroyalreddy/fusion-backend
  tag: latest # this will be override by Jenkins
hpa:
  averageUtilization: 70
db:
  url: jdbc:mysql://prod.db.fusioniq.com:3306/prod?createDatabaseIfNotExist=true
  username: YWRtaW4=
  password: SWtWLVI+eXV3PzxHWWlCVWY1KXc6S0NJZmNERQ==
releaseVersion: release-v1.0.0