deployment:
  replicas: 1
  environment: blue
image:
  repository: iamroyalreddy/fusion-fe
  tag: latest
hpa:
  averageUtilization: 70
ingress:
  name: fusioniq # Changed from 'web' to match Ingress metadata.name
  scheme: internet-facing
  targetType: ip
  tags: Environment=prod,Team=test,Project=fusioniq
  group: fusioniq
  host: royalreddy.site
  subnets:
    - subnet-0e016de018edc0d41
    - subnet-0f6a5a04ee8ae931d
releaseVersion: realise-v1.0.0