deployment:
  replicas: 1
  environment: blue
image:
  repository: iamroyalreddy/fusion-fe
  tag: latest
hpa:
  averageUtilization: 70
ingress:
  name: fusioniq # Changed from 'web' to match Ingress metadata.name
  scheme: internet-facing
  targetType: ip
  tags: Environment=prod,Project=fusioniq,environment=green
  group: fusioniq
  host: royalreddy.site
  subnets:
    - subnet-0b448e9d8091297f7
    - subnet-05942f1ed2a384334
releaseVersion: realise-v1.0.0